language: ruby
rvm:
  - 2.0.0
  - 2.1.2
# uncomment this line if your project needs to run something other than `rake`:
script:
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rspec spec
before_script:
  - cp config/database.travis.yml config/database.yml
  - psql -c 'create database phrug' -U postgres
